version: "3"
services: 
  webserver:
    build: './webserver/'
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root